# Generated by Django 2.1.5 on 2019-02-06 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_type', models.CharField(max_length=100)),
                ('blog_date', models.DateField(default=datetime.date(2019, 2, 6))),
                ('cover_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
