# Generated by Django 2.1.5 on 2019-02-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190207_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_author',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
