# Generated by Django 2.1.5 on 2019-02-08 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190207_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_jist',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(default=datetime.date(2019, 2, 8)),
        ),
    ]
