# Generated by Django 2.1.5 on 2019-02-08 15:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190208_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=100)),
                ('comment_date', models.DateField(default=datetime.date(2019, 2, 8))),
                ('comment_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_by', models.CharField(max_length=100)),
                ('reply_content', models.TextField()),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Comment')),
            ],
        ),
    ]
