# Generated by Django 2.1.5 on 2019-02-08 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_reply_reply_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_author_email',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(default=datetime.date(2019, 2, 9)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(default=datetime.date(2019, 2, 9)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_date',
            field=models.DateField(default=datetime.date(2019, 2, 9)),
        ),
    ]
