# Generated by Django 2.1.5 on 2019-02-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_listing',
            name='slider',
            field=models.BooleanField(default=False),
        ),
    ]
