# Generated by Django 2.1.5 on 2019-02-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0002_property_listing_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_listing',
            old_name='photo_3',
            new_name='cover',
        ),
    ]
