# Generated by Django 2.1.5 on 2019-02-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0005_auto_20190206_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_listing',
            name='sale_type',
            field=models.CharField(default='rent', max_length=200),
        ),
    ]
