# Generated by Django 2.1.5 on 2019-02-08 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_is_team'),
        ('property_listing', '0007_inquire'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquire',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agents.Agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquire',
            name='property_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='property_listing.Property_listing'),
            preserve_default=False,
        ),
    ]
