# Generated by Django 2.1.5 on 2019-02-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0008_auto_20190209_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquire',
            name='agent',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='inquire',
            name='property_name',
            field=models.CharField(max_length=300),
        ),
    ]
